#!/usr/bin/env python3
from pydocsis.cmConfig import CmConfig, json_this
import os
import sys
import json

if len(sys.argv) != 2:
    print("no file specified")
    sys.exit(1)
cmConfig = CmConfig()
cmConfig.generate_string_from_file(sys.argv[1])
cmConfig.parse()
bob = cmConfig.toJSON()
print(json.dumps(bob, indent=4))

